package com.bejohnself.passwordmanager.ui.theme

import androidx.compose.ui.graphics.Color

val BluePrimaryLight = Color(0xFF2F6FED)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFDCE4FF)
val BlueOnPrimaryContainerLight = Color(0xFF101C48)
val BlueSecondaryLight = Color(0xFF5A6272)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFDFE7F5)
val BlueOnSecondaryContainerLight = Color(0xFF171E2D)
val BlueTertiaryLight = Color(0xFF00857A)
val BlueOnTertiaryLight = Color(0xFFFFFFFF)
val BlueTertiaryContainerLight = Color(0xFF9EF3E6)
val BlueOnTertiaryContainerLight = Color(0xFF00201C)
val BlueBackgroundLight = Color(0xFFF8F9FC)
val BlueOnBackgroundLight = Color(0xFF1A1C21)
val BlueSurfaceLight = Color(0xFFFBFBFF)
val BlueOnSurfaceLight = Color(0xFF1A1C21)
val BlueSurfaceVariantLight = Color(0xFFE1E2E8)
val BlueOnSurfaceVariantLight = Color(0xFF44474E)
val BlueOutlineLight = Color(0xFF74777F)

val BluePrimaryDark = Color(0xFFB3C7FF)
val BlueOnPrimaryDark = Color(0xFF082F6B)
val BluePrimaryContainerDark = Color(0xFF1B4A99)
val BlueOnPrimaryContainerDark = Color(0xFFDCE4FF)
val BlueSecondaryDark = Color(0xFFC4CAD7)
val BlueOnSecondaryDark = Color(0xFF2D323F)
val BlueSecondaryContainerDark = Color(0xFF444957)
val BlueOnSecondaryContainerDark = Color(0xFFE0E6F4)
val BlueTertiaryDark = Color(0xFF00D5C3)
val BlueOnTertiaryDark = Color(0xFF003731)
val BlueTertiaryContainerDark = Color(0xFF005048)
val BlueOnTertiaryContainerDark = Color(0xFF9EF3E6)
val BlueBackgroundDark = Color(0xFF121316)
val BlueOnBackgroundDark = Color(0xFFE4E2E9)
val BlueSurfaceDark = Color(0xFF121316)
val BlueOnSurfaceDark = Color(0xFFE4E2E9)
val BlueSurfaceVariantDark = Color(0xFF44474E)
val BlueOnSurfaceVariantDark = Color(0xFFC4C6CE)
val BlueOutlineDark = Color(0xFF8E9099)